### ISSUE TITLE
Test Cases

### ISSUE THREAD

**Issue by ZenInTexas** [botengine-de/OnceBot#2]
I am trying to update this project.  Some of the test case files seem to be missing:

locatePattern.cs LocatePatternTestCase()

FileName    = "16.02.07.idle.min.png",

I tried to find this file, but could not.  Was it comitted?

**Comment by Viir** [comment]
I don't remember as it was several years ago.

However, we recently started developing a bot for Elvenar and added training data at https://github.com/Viir/bots/blob/3c41e57a3ef423b9f55ad0cd177aba9e34edb847/implement/applications/elvenar/training-data/2022-03-07-elvenar-djvj-BTqe1xf.bmp

For an overview of the development, see https://forum.botlab.org/t/oncebot-elvenar-bot/103/45?u=viir

**Comment by Viir** [comment]
We also added crops from that training data image for automating the tests of individual patterns at https://github.com/Viir/bots/blob/3c41e57a3ef423b9f55ad0cd177aba9e34edb847/implement/applications/elvenar/elvenar-bot-elm-test/tests/Sample_2022_03_07.elm
